spring:
  application:
    name: kan-ai-cli
  main:
    banner-mode: off
    web-application-type: none
    allow-circular-references: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      base-url: http://ollama:11434
      chat:
        model: llama3.2
    chat:
      client:
        enabled: false

# Tracing configuration
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces

# OpenTelemetry configuration
otel:
  exporter:
    otlp:
      endpoint: http://tempo:4318
  traces:
    exporter: otlp

logging:
  level:
    root: ERROR
    io.micrometer.tracing: INFO
    io.opentelemetry: DEBUG